import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import Header from "./Component/Header/header";

const poppins= Poppins({
  subsets: ['latin'], // You can choose different subsets
  weight: ['400', '500','700'], // Include different font weights (optional)
  style: ['normal'],
 })

export const metadata: Metadata = {
  title: "ArcStore Policy Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className }
      >
        <Header></Header>
         
        {children}
      </body>
    </html>
  );
}
